model:
  backbone:
    name: "resnet18"
    pretrained: True
    out_indices: [2, 3, 4]
    frozen_stages: 1
  neck:
    name: "fpn"
    out_channels: 256
    use_bias: True
  head:
    num_proposals: 300
    hidden_dim: 256
    dim_feedforward: 512
    num_heads: 4
    num_classes: 80
    dropout: 0.3

    num_cls: 1
    num_reg: 3
    num_dynamic: 2
    dim_dynamic: 64
matcher:
  cost_class: 2.0
  cost_bbox: 5.0
  cost_giou: 2.0
  use_focal: True
  alpha: 0.25
  gamma: 2.0
  ota_k: 5             # SimOTA k (dynamic matching)

loss:
  weight_dict:
    loss_ce: 2.0
    loss_bbox: 5.0
    loss_giou: 2.0
  eos_coef: 0.1